name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python:
        - 3.9
        platform:
        - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox
          python -m pip freeze --all
      - name: Run tests
        run: tox -v
